SYSTEM_PROMPTS_PATH: 'assets/system_prompts'
RSS_SOURCES:
  - name: 'fox'
    url: 'https://moxie.foxnews.com/google-publisher/latest.xml'
TEST_HOST: '127.0.0.1'
TEST_PORT: 54321
ALLOWED_ORIGINS:
  - 'http://localhost:3000'
  - 'http://127.0.0.1:54321'